spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=product
spring.datasource.password=product

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.mvc.problemdetails.enabled=true
logging.level.com.diako.product_service=INFO